project_name: olive

before:
  hooks:
    - go mod tidy

builds:
  - binary: olive

    main: ./
    env:
      - CGO_ENABLED=0
      
    ldflags:
      - -s -w -X github.com/go-olive/olive/command.build={{.Tag}}

    goos:
      - linux
      - windows
    goarch:
      - amd64

changelog:
  skip: true

archives:
  - id: olive
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - zarf/tmpl/config.toml

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"
